version: "3.8"

services:
  calibre-web:
    image: ghcr.io/linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${SYS_TIMEZONE}
      - DOCKER_MODS=linuxserver/calibre-web:calibre
    volumes:
      - '${CALIBRE_CONFIG}:/config'
      - '${CALIBRE_LIBRARY}:/books'
    ports:
      - 8083:8083
    restart: unless-stopped
