version: "3.8"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: always
    
    environment:
      TZ: '${PIHOLE_TIMEZONE}'          # set your timezone
      WEBPASSWORD: '${PIHOLE_PASSWORD}' # set your password
    
    network_mode: host
    
    volumes:
      - '~/.pihole/etc-pihole/:/etc/pihole/'
      - '~/.pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    
    # Required for the DHCP server
    cap_add:
      - NET_ADMIN
